apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dgozalo
    provider: github
    repository: gkessotestcjxd612
  name: dgozalo-gkessotestcjxd612
spec:
  description: Imported application for dgozalo/gkessotestcjxd612
  httpCloneURL: https://github.com/dgozalo/gkessotestcjxd612.git
  org: dgozalo
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: gkessotestcjxd612
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dgozalo/gkessotestcjxd612.git
