adminUser:
  password: vault:cjxd-v6-gke/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dgozalo@cloudbees.com
  token: vault:cjxd-v6-gke/pipelineUser:token
  username: dgozalo
prow:
  hmacToken: vault:cjxd-v6-gke/prow:hmacToken
